// const err = new Error("Error arrived");
// console.log(err.stack);

// const {CustomError} = require('./CustomEror');
// throw new CustomError('Error arrived');

try{
    dosomething();
}
catch(e){
    console.log(e);
    console.log("error arrived");
    
}








